<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Crypto_Website.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTO\" />
    <Folder Include="Interface\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crypto-Website.Domain\Crypto-Website.Domain.csproj" />
  </ItemGroup>

</Project>
