<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Crypto_Website.Infrastructure</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="Repository\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crypto-Website.Application\Crypto-Website.Application.csproj" />
    <ProjectReference Include="..\Crypto-Website.Domain\Crypto-Website.Domain.csproj" />
  </ItemGroup>

</Project>
